
#!/bin/bash

echo "🚀 Starting comprehensive GitHub upload with enhanced CodePilot features..."

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "Initializing Git repository..."
    git init
    git branch -M main
fi

# Install/reinstall dependencies to ensure @octokit/rest is properly installed
echo "📦 Installing dependencies including @octokit/rest..."
npm install

# Show current status
echo "📊 Current Git status:"
git status --short

# Add all files to staging
echo "📁 Adding all files to Git staging area..."
git add .

# Create comprehensive commit message with timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
COMMIT_MSG="Enhanced CodePilot with complete GitHub integration - $TIMESTAMP

Features added:
- Enhanced GitHub integration with additional action buttons
- Push Code to GitHub functionality with validation
- Open Repository button for quick access
- Clear Form button for easy reset
- Quick Setup with default values
- Copy Repository URL functionality
- Improved error handling and user feedback
- Python code generation validation
- Complete PyInstaller Builder for executable generation
- Android Studio compilation documentation
- All UI components and configurations

Generated by: CodePilot GitHub Integration System"

echo "💾 Committing changes..."
if git commit -m "$COMMIT_MSG"; then
    echo "✅ Commit successful!"
else
    echo "⚠️ No changes to commit or commit failed."
fi

# Check if remote origin exists
if ! git remote get-url origin > /dev/null 2>&1; then
    echo "❗ No remote repository configured."
    echo "Please add your GitHub repository URL:"
    echo "git remote add origin https://github.com/username/repository-name.git"
    echo "Then run this script again."
    exit 1
fi

# Show remote info
echo "🔗 Remote repository:"
git remote get-url origin

# Push to GitHub
echo "🌐 Pushing to GitHub..."
if [ ! -z "$GITHUB_TOKEN" ]; then
    echo "Using GITHUB_TOKEN for authentication..."
    # Configure Git to use the token
    git config --global credential.helper store
    echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > ~/.git-credentials
fi

# Push with detailed output
if git push -u origin main --verbose; then
    echo "✅ Successfully uploaded all files to GitHub!"
    echo "🎉 Your enhanced CodePilot application is now available on GitHub!"
else
    echo "❌ Push failed. Please check your credentials and repository permissions."
    echo "💡 Tips:"
    echo "   - Make sure your GITHUB_TOKEN is set if using token authentication"
    echo "   - Verify repository URL is correct"
    echo "   - Check if you have write permissions to the repository"
    exit 1
fi
echo "📋 Upload summary:"
echo "   - All source code and components"
echo "   - GitHub integration with @octokit/rest"
echo "   - PyInstaller Builder"
echo "   - Android development documentation"
echo "   - Test files and configurations"
echo "   - Dependencies properly installed"

echo ""
echo "🔧 To set up on a new machine:"
echo "   1. Clone the repository"
echo "   2. Run: npm install"
echo "   3. Set up environment variables in .env.local"
echo "   4. Run: npm run dev"
